### PR TITLE
Updated user ineteractions and UI

### PR DESCRIPTION
**Pull request by kidus-worku**
You can ignore the "Project.xml" and the gradle related files, I update my gradle and that's why it's there.

### CODE REVIEW

**Comment by Nahom-ab** [comment]
@kidus-worku  you should add the project.xml to your .gitignore. since it is only related to you. it might create problems in the future pulls.
why did you update the gradle file...did something force you to?

**Comment by kidus-worku** [comment]
@Nahom-ab no Android studio notified me that there's a newer version of Gradle, that's why I updated it and I'm kinda new to git so let me check out how to do "gitignore" thing you mentioned, so does this mean that you can't pull the files unless I do gitignore?

**Comment by Nahom-ab** [comment]
@kidus-worku 
1. yeah it does that, but i think we should use the gradle versions that were used when the project was created. because it was set by android studio when i first initialized the project.  just to avoid any issues with it.
2. basically .gitignore tells git not to push or track the files listed in it. .gitignore will be in your main project folder. look at how other files are put there and add it like so.

**Comment by Nahom-ab** [comment]
I am afraid you have to fix those and create a new PR from the new commit. because
1. your Project.xml file is not the same as mine or other members's so when i or one of them pull from the repo in the future, it will create a conflict and project related errors.
2. the gradle upgrade also might create unforeseen issues in the future. one scenario being, a depreciated command or build config on the newer version.

**Comment by kidus-worku** [comment]
Yea now it will no longer push those, but I think it's better if I redo everything fork the main repo again and do it all over again, it wouldn't take that much time

**Comment by Nahom-ab** [comment]
Yeah sure, if that is what you want to do, but you could just push a new commit with the fix and create a PR to it. seems simpler.

**Comment by kidus-worku** [comment]
Yea but I think it's better to start it with a clean plate, and did u already pull ende?

**Comment by Nahom-ab** [comment]
No, i didn't...your PR is not merged yet eko...so nowhere to pull from...lol

**Comment by Nahom-ab** [comment]
the good thing is github tells me **This branch has no conflicts with the base branch**. thats a good sign. just those fixes and your done.

**Comment by kidus-worku** [comment]
🤣 I need to get more educated on this Git stuff 😂 and I'll cancel this request and I'll let u know when I'm done

**Comment by Nahom-ab** [comment]
okay, lets keep this PR open for others to see and learn from your mistakes...lol

**Comment by kidus-worku** [comment]
lol sure but would this PR still exist after I deleted the repository?

**Pull request closed without merging**
